version: '3.8'

services:
  backend:
    build: ./lureon-backend
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/lureon

  frontend:
    build: ./lureon-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    build: ./lureon-mongoDB
    ports:
      - "27017:27017"
